name: DinD Build & DinD Push to container registry

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    paths:
      - "Dockerfile.qemu"

jobs:
  docker:
    uses: nezuchan/workflows/.github/workflows/docker-build.yml@main
    secrets: inherit